[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

# Proxy API requests to serverless function
[[redirects]]
  from = "/api/*"
  to = "/.functions/server"
  status = 200
  force = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [functions]
  directory = "functions"


# Cache static assets with proper headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for the site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' *.firebaseio.com firestore.googleapis.com identitytoolkit.googleapis.com; font-src 'self' data:;"
